# prompts.yaml
# Defines an ordered list of stages and the prompt text that will be sent to the LLM
# for each stage. Modify prompts or stage order as needed.
# Grouped by attack type (SSH Brute Force, Port 80 Attack, DoS)
# and operational purpose (Recon, Data Capture/Destruction, Denial, Privilege Checks, Defense).

stages:

  # Base Usage
  - name: ping
    prompt: >
      You are an automated cyber agent operating inside a closed cyber range.
      Reply with only a single valid JSON object and nothing else
      (no explanations, no code fences, no extra text). Use double quotes only.
      The JSON must follow this schema:
      {"tool": "<tool name>", "params": { ... }}
      Allowed tool values: ping
      The 'target' parameter must be a single IPv4 address (for example, 192.168.100.2).
      Example valid response:
      {"tool":"ping","params":{"target":"192.168.100.2","count":1}}

  - name: nmap
    prompt: >
      You are an automated agent tasked with scanning the target for open ports and services.
      Reply with only a single valid JSON object and nothing else (no explanations, no code fences, no text).
      Use double quotes only.
      The JSON must follow this schema:
      {"tool": "<tool name>", "params": { ... }}
      Allowed tool values: nmap, ping, tcpdump, iptables, hydra, simulator.
      The 'target' parameter must be a cidr address (e.g., 192.168.100.2).
      Use only whitelisted flags defined in whitelist.yaml.
      If you need multiple flags, return them as an array under "flags_list" (for example ["-sS","-A"]) instead of a combined string.
      Example valid responses:
      {"tool":"nmap","params":{"target":"192.168.100.2","flags":"-sV"}}
      {"tool":"nmap","params":{"target":"192.168.100.2","flags_list":["-sS","-A"]}}

  - name: hydra
    prompt: >
      STAGE: HYDRA
      You are simulating an SSH brute-force attempt against the target.
      Reply with only a single valid JSON object and nothing else (no explanation, no code fences, no text).
      The JSON must use double quotes only and match this schema:
      {"tool":"hydra","params":{"target":"<ipv4>","username":"<username>","wordlist":"<allowed_path>","max_attempts":<int>}}
      The 'target' must be a single IPv4 address (e.g., 192.168.100.2).
      The 'username' must be provided; if not known, use "admin".
      The 'wordlist' must be one of the allowed paths in whitelist.yaml (e.g., /usr/share/wordlists/rockyou.txt).
      'max_attempts' should be between 1 and 1000.
      Example valid response:
      {"tool":"hydra","params":{"target":"192.168.100.2","username":"admin","wordlist":"/usr/share/wordlists/rockyou.txt","max_attempts":100}}

  # Attack Category Stages
  - name: ssh_bruteforce_variant
    prompt: >
      You are simulating an SSH brute-force attempt against the target.
      Reply with only a single valid JSON object and nothing else (no explanation, no code fences, no text).
      The JSON must use double quotes only and match this schema:
      {"tool":"hydra","params":{"target":"<ipv4>","username":"<username>","wordlist":"<allowed_path>","max_attempts":<int>}}
      The 'target' must be a single IPv4 address (e.g., 192.168.100.2).
      The 'username' must be provided; if not known, use "admin".
      The 'wordlist' must be one of the allowed paths in whitelist.yaml (e.g., /usr/share/wordlists/rockyou.txt).
      'max_attempts' should be between 1 and 1000.
      Example valid response:
      {"tool":"hydra","params":{"target":"192.168.100.2","username":"admin","wordlist":"/usr/share/wordlists/rockyou.txt","max_attempts":100}}


  - name: smb_enum_exfil
    prompt: >
      You are performing SMB enumeration followed by simulated file exfiltration.
      Respond only with a single valid JSON object.
      Schema:
      {"tool":"smb","params":{"target":"192.168.60.3","share":"\\\\192.168.60.3\\public","action":"enum_and_exfil","filename":"Employees.xlsx"}}
      Allowed tool value: smb (or simulator if smb is blocked).
      The 'share' field must be a UNC path such as "\\\\192.168.60.3\\public".
      The 'filename' should represent a discovered file in the share.
      Example:
      {"tool":"smb","params":{"target":"192.168.60.3","share":"\\\\192.168.60.3\\public","action":"enum_and_exfil","filename":"Employees.xlsx"}}
  

  - name: dos_attack
    prompt: >
      You are simulating a denial-of-service operation designed to stress a target system.
      Respond only with a valid JSON object.
      Schema:
      {"tool":"hping3","params":{"target":"192.168.60.2","duration":60,"intensity":5}}
      Allowed tool values: hping3, iptables (for defensive response), or ping (for load simulation).
      Example:
      {"tool":"hping3","params":{"target":"192.168.60.2","duration":60,"intensity":5}}

  # Purpose Category Stages
  - name: recon_additional_servers
    prompt: >
      PURPOSE: Recon of additional servers beyond Blue.
      You are tasked with mapping the network to discover additional systems beyond the known Blue host.
      Respond with only a single valid JSON object.
      Schema:
      {"tool":"nmap","params":{"target":"192.168.100.0/24","flags":"-A"}}
      Example:
      {"tool":"nmap","params":{"target":"192.168.100.0/24","flags":"-A"}}

  - name: capture_destroy_data
    prompt: >
      PURPOSE (SIMULATION ONLY): Capture and mark files for deletion.
      THIS STAGE IS AN EXPLICIT SIMULATION-ONLY ALIAS and MUST return tool="simulator".
      **Do NOT perform any real file operations.**
      Schema:
      {"tool":"simulator","params":{"target":"<ipv4>","filename":"<string>","action":"capture_and_send","result":"<success|partial|failure>","message":"<note>"}}
      Example:
      {"tool":"simulator","params":{"target":"192.168.60.3","filename":"Super important information","action":"capture_and_send","result":"success","message":"simulated: file staged to red (no-op)"}}

  - name: deny_web_services
    prompt: >
      PURPOSE (SIMULATION ONLY): Denial of web services.
      THIS STAGE IS AN EXPLICIT SIMULATION-ONLY ALIAS and MUST return tool="simulator".
      **Do NOT run iptables or service commands.**
      Schema:
      {"tool":"simulator","params":{"target":"<ipv4>","port":80,"action":"block_incoming|block_outgoing|service_stop","result":"<success|partial|failure>","message":"<note>"}}
      Example:
      {"tool":"simulator","params":{"target":"192.168.60.3","port":80,"action":"block_incoming","result":"success","message":"simulated: port 80 blocked (no-op)"}}

  - name: check_privileges
    prompt: >
      PURPOSE: Check account privileges.
      Respond with only a single valid JSON object describing the account privileges (simulation-only).
      Schema:
      {"tool":"check_privileges","params":{"target":"192.168.60.3","user":"admin","privilege_level":"sudo","message":"user has sudo privileges"}}
      Example:
      {"tool":"check_privileges","params":{"target":"192.168.60.3","user":"admin","privilege_level":"sudo","message":"user has sudo privileges"}}

  # Defense Stages
  - name: firewall_update
    prompt: >
      STAGE: FIREWALL UPDATE
      You are an automated cyber defense AI agent. Reply with only a single valid JSON object and nothing else.
      Use double quotes only. The JSON must follow this schema:
      {"tool":"iptables","params":{"action":"<action>","chain":"<chain>","rule":"<rule>","src":"<ipv4_or_cidr>"}}
      THIS STAGE REQUIRES tool = "iptables". Do NOT return any other tool value.
      The 'src' parameter must be provided; use "0.0.0.0/0" if the rule applies to all sources.
      Example valid response:
      {"tool":"iptables","params":{"action":"add","chain":"INPUT","rule":"-p tcp --dport 22 -j DROP","src":"0.0.0.0/0"}}

  - name: intrusion_detection
    prompt: >
      STAGE: INTRUSION DETECTION
      You are an automated cyber defense AI agent. Reply with only a single valid JSON object and nothing else.
      Use double quotes only. The JSON must follow this schema:
      {"tool":"blue_detection_agent","params":{"script":"blue_detection_agent.py"}}
      THIS STAGE REQUIRES tool = "blue_detection_agent". Do NOT return any other tool value.
      Example valid response:
      {"tool":"blue_detection_agent","params":{"script":"blue_detection_agent.py"}}

  - name: system_hardening
    prompt: >
      STAGE: SYSTEM HARDENING
      You are an automated cyber defense AI agent. Reply with only a single valid JSON object and nothing else.
      Use double quotes only. The JSON must follow this schema:
      {"tool":"blue_detection_agent.py","params":{"target":"<ipv4>","flags":"<allowed_flags>"}}
      THIS STAGE REQUIRES tool = "nmap". Do NOT return any other tool value.
      Example valid response:
      {"tool":"nmap","params":{"target":"192.168.100.3","flags":"-sS"}}

  - name: sudo_harden
    prompt: >
      STAGE: SUDO HARDEN / USER PRIVILEGE DESCALATION
      You are an automated cyber defense AI agent. Reply with only a single valid JSON object.
      Schema:
      {"tool":"simulator","params":{"target":"<ipv4>","user":"<username>","action":"harden_sudo","result":"<success|partial|failure>","message":"<note>"}}
      Example:
      {"tool":"simulator","params":{"target":"192.168.60.3","user":"admin","action":"harden_sudo","result":"success","message":"simulated: sudo rights reduced or locked (no-op)"}}

  # Simulation Helper Stages
  - name: capture_destroy_file_simulation
    prompt: >
      PURPOSE (SIMULATION ONLY): Simulate capturing and simulated removal of a named file.
      **Do NOT perform any real file operations.**
      Schema:
      {"tool":"simulator","params":{"target":"<ipv4>","filename":"<string>","result":"<success|partial|failure>","message":"<note>"}}
      Example:
      {"tool":"simulator","params":{"target":"192.168.60.3","filename":"Super important information","result":"success","message":"Simulated: file captured and deletion simulated"}}

  - name: close_port80_simulation
    prompt: >
      PURPOSE (SIMULATION ONLY): Simulate closing or blocking HTTP (port 80).
      **Do NOT run iptables or service commands.**
      Schema:
      {"tool":"simulator","params":{"target":"<ipv4>","port":80,"result":"<success|partial|failure>","message":"<note>"}}
      Example:
      {"tool":"simulator","params":{"target":"192.168.60.3","port":80,"result":"success","message":"Simulated: port 80 blocked (no-op)"}}
